version: "3"

services:
  webserver:
    build:
      context: ./docker/bin
    container_name: docker-lumen
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./docker/vhost:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html