version: "3"

services:
  webserver:
    build:
      context: ./docker/bin
    container_name: simplest-docker
    restart: 'always'
    ports:
      - "1234:80"
      - "123:443"
    volumes:
      - ./www:/var/www/html
      - ./docker/vhost:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html